spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://l9dwvv6j64hlhpul.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/vo94t1wtydjnzrc2
    username: mb75hfnd9qmwkbdy
    password: i9xt64x6pmh2ebh9
